CREATE TABLE `PVPETRIS` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(32) NOT NULL,
  `SCORE` int(11) NOT NULL,
  `BURN` int(11) NOT NULL,
  `TTR` int(11) DEFAULT NULL,
  `STARTLEVEL` int(11) NOT NULL,
  `PLAYDATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

ALTER TABLE `PVPETRIS`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `PVPETRIS`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
